// Six curated, harmonious colour palettes. Each one sets every colour token
// across the booking page so practitioners can pick a mood in one click and
// trust the result looks clean and consistent.

import type { ClinicThemeInput } from "@/lib/theme.functions";

export type ColorPaletteKey =
  | "warm-sand"
  | "noir-gold"
  | "soft-botanical"
  | "clean-slate"
  | "blush-atelier"
  | "ocean-calm";

export type ColorPalette = {
  key: ColorPaletteKey;
  name: string;
  tagline: string;
  swatches: string[]; // shown in the picker
  colors: Partial<ClinicThemeInput>;
};

export const COLOR_PALETTES: ColorPalette[] = [
  {
    key: "warm-sand",
    name: "Warm Sand",
    tagline: "Soft cream with warm taupe — welcoming, premium.",
    swatches: ["#faf7f2", "#f0ebe3", "#8b7355", "#3a3530"],
    colors: {
      background_color: "#faf7f2",
      text_color: "#3a3530",
      primary_color: "#8b7355",
      accent_color: "#c9b99a",
      header_bg_color: "#faf7f2",
      header_text_color: "#3a3530",
      footer_bg_color: "#3a3530",
      footer_text_color: "#faf7f2",
      menu_card_bg: "#ffffff",
      menu_card_border_color: "#ece6db",
      menu_category_bg: "#3a3530",
      menu_category_text: "#faf7f2",
      menu_treatment_name_color: "#3a3530",
      menu_price_color: "#8b7355",
      button_color: "#3a3530",
      button_text_color: "#faf7f2",
      welcome_card_bg_color: "#ffffff",
      welcome_card_border_color: "#ece6db",
      contact_tile_bg_color: "#ffffff",
      contact_tile_border_color: "#ece6db",
      hero_overlay_color: "#3a3530",
    },
  },
  {
    key: "noir-gold",
    name: "Noir & Gold",
    tagline: "Inky black with antique gold — high-end, editorial.",
    swatches: ["#0d0d0d", "#1a1a1a", "#c9a84c", "#f5f1e6"],
    colors: {
      background_color: "#f5f1e6",
      text_color: "#0d0d0d",
      primary_color: "#0d0d0d",
      accent_color: "#c9a84c",
      header_bg_color: "#0d0d0d",
      header_text_color: "#f5f1e6",
      footer_bg_color: "#0d0d0d",
      footer_text_color: "#f5f1e6",
      menu_card_bg: "#ffffff",
      menu_card_border_color: "#e8e2d2",
      menu_category_bg: "#0d0d0d",
      menu_category_text: "#c9a84c",
      menu_treatment_name_color: "#0d0d0d",
      menu_price_color: "#0d0d0d",
      button_color: "#0d0d0d",
      button_text_color: "#f5f1e6",
      welcome_card_bg_color: "#ffffff",
      welcome_card_border_color: "#e8e2d2",
      contact_tile_bg_color: "#ffffff",
      contact_tile_border_color: "#e8e2d2",
      hero_overlay_color: "#0d0d0d",
    },
  },
  {
    key: "soft-botanical",
    name: "Soft Botanical",
    tagline: "Sage green on ivory — calm, natural, fresh.",
    swatches: ["#f6f4ee", "#dce5d4", "#7d9b76", "#2f3e2c"],
    colors: {
      background_color: "#f6f4ee",
      text_color: "#2f3e2c",
      primary_color: "#7d9b76",
      accent_color: "#a8c0a0",
      header_bg_color: "#f6f4ee",
      header_text_color: "#2f3e2c",
      footer_bg_color: "#2f3e2c",
      footer_text_color: "#f6f4ee",
      menu_card_bg: "#ffffff",
      menu_card_border_color: "#e3e7da",
      menu_category_bg: "#2f3e2c",
      menu_category_text: "#f6f4ee",
      menu_treatment_name_color: "#2f3e2c",
      menu_price_color: "#7d9b76",
      button_color: "#2f3e2c",
      button_text_color: "#f6f4ee",
      welcome_card_bg_color: "#ffffff",
      welcome_card_border_color: "#e3e7da",
      contact_tile_bg_color: "#ffffff",
      contact_tile_border_color: "#e3e7da",
      hero_overlay_color: "#2f3e2c",
    },
  },
  {
    key: "clean-slate",
    name: "Clean Slate",
    tagline: "Crisp white with deep navy — modern, professional.",
    swatches: ["#ffffff", "#f1f4f8", "#0f1b3d", "#3b6fa0"],
    colors: {
      background_color: "#ffffff",
      text_color: "#0f1b3d",
      primary_color: "#0f1b3d",
      accent_color: "#3b6fa0",
      header_bg_color: "#ffffff",
      header_text_color: "#0f1b3d",
      footer_bg_color: "#0f1b3d",
      footer_text_color: "#ffffff",
      menu_card_bg: "#ffffff",
      menu_card_border_color: "#e4e8ef",
      menu_category_bg: "#0f1b3d",
      menu_category_text: "#ffffff",
      menu_treatment_name_color: "#0f1b3d",
      menu_price_color: "#3b6fa0",
      button_color: "#0f1b3d",
      button_text_color: "#ffffff",
      welcome_card_bg_color: "#ffffff",
      welcome_card_border_color: "#e4e8ef",
      contact_tile_bg_color: "#ffffff",
      contact_tile_border_color: "#e4e8ef",
      hero_overlay_color: "#0f1b3d",
    },
  },
  {
    key: "blush-atelier",
    name: "Blush Atelier",
    tagline: "Soft blush with cocoa — feminine, refined.",
    swatches: ["#fbf3ef", "#f3dcd2", "#a4655a", "#3d2723"],
    colors: {
      background_color: "#fbf3ef",
      text_color: "#3d2723",
      primary_color: "#a4655a",
      accent_color: "#d49a8b",
      header_bg_color: "#fbf3ef",
      header_text_color: "#3d2723",
      footer_bg_color: "#3d2723",
      footer_text_color: "#fbf3ef",
      menu_card_bg: "#ffffff",
      menu_card_border_color: "#f0dcd3",
      menu_category_bg: "#3d2723",
      menu_category_text: "#fbf3ef",
      menu_treatment_name_color: "#3d2723",
      menu_price_color: "#a4655a",
      button_color: "#3d2723",
      button_text_color: "#fbf3ef",
      welcome_card_bg_color: "#ffffff",
      welcome_card_border_color: "#f0dcd3",
      contact_tile_bg_color: "#ffffff",
      contact_tile_border_color: "#f0dcd3",
      hero_overlay_color: "#3d2723",
    },
  },
  {
    key: "ocean-calm",
    name: "Ocean Calm",
    tagline: "Off-white with deep teal — serene, spa-like.",
    swatches: ["#f4f7f6", "#cfe0dd", "#1a4a4f", "#0c2227"],
    colors: {
      background_color: "#f4f7f6",
      text_color: "#0c2227",
      primary_color: "#1a4a4f",
      accent_color: "#5cbdb9",
      header_bg_color: "#f4f7f6",
      header_text_color: "#0c2227",
      footer_bg_color: "#0c2227",
      footer_text_color: "#f4f7f6",
      menu_card_bg: "#ffffff",
      menu_card_border_color: "#dde7e5",
      menu_category_bg: "#0c2227",
      menu_category_text: "#f4f7f6",
      menu_treatment_name_color: "#0c2227",
      menu_price_color: "#1a4a4f",
      button_color: "#0c2227",
      button_text_color: "#f4f7f6",
      welcome_card_bg_color: "#ffffff",
      welcome_card_border_color: "#dde7e5",
      contact_tile_bg_color: "#ffffff",
      contact_tile_border_color: "#dde7e5",
      hero_overlay_color: "#0c2227",
    },
  },
];
