/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhoItsForRouteImport } from './routes/who-its-for'
import { Route as PrescriberHubRouteImport } from './routes/prescriber-hub'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MSlugRouteImport } from './routes/m.$slug'
import { Route as FTokenRouteImport } from './routes/f.$token'
import { Route as CTokenRouteImport } from './routes/c.$token'
import { Route as BookSlugRouteImport } from './routes/book.$slug'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as MSlugIndexRouteImport } from './routes/m.$slug.index'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as MSlugReviewsRouteImport } from './routes/m.$slug.reviews'
import { Route as MSlugQuizRouteImport } from './routes/m.$slug.quiz'
import { Route as MSlugBookMultiRouteImport } from './routes/m.$slug.book-multi'
import { Route as MSlugAuthRouteImport } from './routes/m.$slug.auth'
import { Route as MSlugAccountRouteImport } from './routes/m.$slug.account'
import { Route as MSlugAboutRouteImport } from './routes/m.$slug.about'
import { Route as AuthenticatedDashboardTreatmentsRouteImport } from './routes/_authenticated/dashboard.treatments'
import { Route as AuthenticatedDashboardSettingsRouteImport } from './routes/_authenticated/dashboard.settings'
import { Route as AuthenticatedDashboardServicesRouteImport } from './routes/_authenticated/dashboard.services'
import { Route as AuthenticatedDashboardReviewsRouteImport } from './routes/_authenticated/dashboard.reviews'
import { Route as AuthenticatedDashboardQuizRouteImport } from './routes/_authenticated/dashboard.quiz'
import { Route as AuthenticatedDashboardPractitionersRouteImport } from './routes/_authenticated/dashboard.practitioners'
import { Route as AuthenticatedDashboardPoliciesRouteImport } from './routes/_authenticated/dashboard.policies'
import { Route as AuthenticatedDashboardPaymentsRouteImport } from './routes/_authenticated/dashboard.payments'
import { Route as AuthenticatedDashboardPatientsRouteImport } from './routes/_authenticated/dashboard.patients'
import { Route as AuthenticatedDashboardPackagesRouteImport } from './routes/_authenticated/dashboard.packages'
import { Route as AuthenticatedDashboardNewAppointmentRouteImport } from './routes/_authenticated/dashboard.new-appointment'
import { Route as AuthenticatedDashboardModelSlotsRouteImport } from './routes/_authenticated/dashboard.model-slots'
import { Route as AuthenticatedDashboardMenuRouteImport } from './routes/_authenticated/dashboard.menu'
import { Route as AuthenticatedDashboardMedicalFormsRouteImport } from './routes/_authenticated/dashboard.medical-forms'
import { Route as AuthenticatedDashboardLocationsRouteImport } from './routes/_authenticated/dashboard.locations'
import { Route as AuthenticatedDashboardDiscountsRouteImport } from './routes/_authenticated/dashboard.discounts'
import { Route as AuthenticatedDashboardConsentFormsRouteImport } from './routes/_authenticated/dashboard.consent-forms'
import { Route as AuthenticatedDashboardClinicRouteImport } from './routes/_authenticated/dashboard.clinic'
import { Route as AuthenticatedDashboardCategoriesRouteImport } from './routes/_authenticated/dashboard.categories'
import { Route as AuthenticatedDashboardBrandingRouteImport } from './routes/_authenticated/dashboard.branding'
import { Route as AuthenticatedDashboardBookingsRouteImport } from './routes/_authenticated/dashboard.bookings'
import { Route as AuthenticatedDashboardBookingFlowRouteImport } from './routes/_authenticated/dashboard.booking-flow'
import { Route as AuthenticatedDashboardBioRouteImport } from './routes/_authenticated/dashboard.bio'
import { Route as AuthenticatedDashboardAvailabilityRouteImport } from './routes/_authenticated/dashboard.availability'
import { Route as AuthenticatedDashboardAiImportRouteImport } from './routes/_authenticated/dashboard.ai-import'
import { Route as AuthenticatedDashboardAftercareRouteImport } from './routes/_authenticated/dashboard.aftercare'
import { Route as AuthenticatedDashboardAddonsRouteImport } from './routes/_authenticated/dashboard.addons'
import { Route as AuthenticatedDashboardPatientsIndexRouteImport } from './routes/_authenticated/dashboard.patients.index'
import { Route as AuthenticatedDashboardConsultationsIndexRouteImport } from './routes/_authenticated/dashboard.consultations.index'
import { Route as MSlugManageTokenRouteImport } from './routes/m.$slug.manage.$token'
import { Route as MSlugBookTreatmentIdRouteImport } from './routes/m.$slug.book.$treatmentId'
import { Route as AuthenticatedDashboardPatientsIdRouteImport } from './routes/_authenticated/dashboard.patients.$id'
import { Route as AuthenticatedDashboardConsultationsIdRouteImport } from './routes/_authenticated/dashboard.consultations.$id'

const WhoItsForRoute = WhoItsForRouteImport.update({
  id: '/who-its-for',
  path: '/who-its-for',
  getParentRoute: () => rootRouteImport,
} as any)
const PrescriberHubRoute = PrescriberHubRouteImport.update({
  id: '/prescriber-hub',
  path: '/prescriber-hub',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MSlugRoute = MSlugRouteImport.update({
  id: '/m/$slug',
  path: '/m/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FTokenRoute = FTokenRouteImport.update({
  id: '/f/$token',
  path: '/f/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const CTokenRoute = CTokenRouteImport.update({
  id: '/c/$token',
  path: '/c/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const BookSlugRoute = BookSlugRouteImport.update({
  id: '/book/$slug',
  path: '/book/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const MSlugIndexRoute = MSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MSlugRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const MSlugReviewsRoute = MSlugReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => MSlugRoute,
} as any)
const MSlugQuizRoute = MSlugQuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => MSlugRoute,
} as any)
const MSlugBookMultiRoute = MSlugBookMultiRouteImport.update({
  id: '/book-multi',
  path: '/book-multi',
  getParentRoute: () => MSlugRoute,
} as any)
const MSlugAuthRoute = MSlugAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => MSlugRoute,
} as any)
const MSlugAccountRoute = MSlugAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => MSlugRoute,
} as any)
const MSlugAboutRoute = MSlugAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => MSlugRoute,
} as any)
const AuthenticatedDashboardTreatmentsRoute =
  AuthenticatedDashboardTreatmentsRouteImport.update({
    id: '/treatments',
    path: '/treatments',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardSettingsRoute =
  AuthenticatedDashboardSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardServicesRoute =
  AuthenticatedDashboardServicesRouteImport.update({
    id: '/services',
    path: '/services',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardReviewsRoute =
  AuthenticatedDashboardReviewsRouteImport.update({
    id: '/reviews',
    path: '/reviews',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardQuizRoute =
  AuthenticatedDashboardQuizRouteImport.update({
    id: '/quiz',
    path: '/quiz',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardPractitionersRoute =
  AuthenticatedDashboardPractitionersRouteImport.update({
    id: '/practitioners',
    path: '/practitioners',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardPoliciesRoute =
  AuthenticatedDashboardPoliciesRouteImport.update({
    id: '/policies',
    path: '/policies',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardPaymentsRoute =
  AuthenticatedDashboardPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardPatientsRoute =
  AuthenticatedDashboardPatientsRouteImport.update({
    id: '/patients',
    path: '/patients',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardPackagesRoute =
  AuthenticatedDashboardPackagesRouteImport.update({
    id: '/packages',
    path: '/packages',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardNewAppointmentRoute =
  AuthenticatedDashboardNewAppointmentRouteImport.update({
    id: '/new-appointment',
    path: '/new-appointment',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardModelSlotsRoute =
  AuthenticatedDashboardModelSlotsRouteImport.update({
    id: '/model-slots',
    path: '/model-slots',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardMenuRoute =
  AuthenticatedDashboardMenuRouteImport.update({
    id: '/menu',
    path: '/menu',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardMedicalFormsRoute =
  AuthenticatedDashboardMedicalFormsRouteImport.update({
    id: '/medical-forms',
    path: '/medical-forms',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardLocationsRoute =
  AuthenticatedDashboardLocationsRouteImport.update({
    id: '/locations',
    path: '/locations',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardDiscountsRoute =
  AuthenticatedDashboardDiscountsRouteImport.update({
    id: '/discounts',
    path: '/discounts',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardConsentFormsRoute =
  AuthenticatedDashboardConsentFormsRouteImport.update({
    id: '/consent-forms',
    path: '/consent-forms',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardClinicRoute =
  AuthenticatedDashboardClinicRouteImport.update({
    id: '/clinic',
    path: '/clinic',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardCategoriesRoute =
  AuthenticatedDashboardCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardBrandingRoute =
  AuthenticatedDashboardBrandingRouteImport.update({
    id: '/branding',
    path: '/branding',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardBookingsRoute =
  AuthenticatedDashboardBookingsRouteImport.update({
    id: '/bookings',
    path: '/bookings',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardBookingFlowRoute =
  AuthenticatedDashboardBookingFlowRouteImport.update({
    id: '/booking-flow',
    path: '/booking-flow',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardBioRoute =
  AuthenticatedDashboardBioRouteImport.update({
    id: '/bio',
    path: '/bio',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAvailabilityRoute =
  AuthenticatedDashboardAvailabilityRouteImport.update({
    id: '/availability',
    path: '/availability',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAiImportRoute =
  AuthenticatedDashboardAiImportRouteImport.update({
    id: '/ai-import',
    path: '/ai-import',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAftercareRoute =
  AuthenticatedDashboardAftercareRouteImport.update({
    id: '/aftercare',
    path: '/aftercare',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAddonsRoute =
  AuthenticatedDashboardAddonsRouteImport.update({
    id: '/addons',
    path: '/addons',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardPatientsIndexRoute =
  AuthenticatedDashboardPatientsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardPatientsRoute,
  } as any)
const AuthenticatedDashboardConsultationsIndexRoute =
  AuthenticatedDashboardConsultationsIndexRouteImport.update({
    id: '/consultations/',
    path: '/consultations/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const MSlugManageTokenRoute = MSlugManageTokenRouteImport.update({
  id: '/manage/$token',
  path: '/manage/$token',
  getParentRoute: () => MSlugRoute,
} as any)
const MSlugBookTreatmentIdRoute = MSlugBookTreatmentIdRouteImport.update({
  id: '/book/$treatmentId',
  path: '/book/$treatmentId',
  getParentRoute: () => MSlugRoute,
} as any)
const AuthenticatedDashboardPatientsIdRoute =
  AuthenticatedDashboardPatientsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedDashboardPatientsRoute,
  } as any)
const AuthenticatedDashboardConsultationsIdRoute =
  AuthenticatedDashboardConsultationsIdRouteImport.update({
    id: '/consultations/$id',
    path: '/consultations/$id',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/features': typeof FeaturesRoute
  '/prescriber-hub': typeof PrescriberHubRoute
  '/who-its-for': typeof WhoItsForRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/book/$slug': typeof BookSlugRoute
  '/c/$token': typeof CTokenRoute
  '/f/$token': typeof FTokenRoute
  '/m/$slug': typeof MSlugRouteWithChildren
  '/dashboard/addons': typeof AuthenticatedDashboardAddonsRoute
  '/dashboard/aftercare': typeof AuthenticatedDashboardAftercareRoute
  '/dashboard/ai-import': typeof AuthenticatedDashboardAiImportRoute
  '/dashboard/availability': typeof AuthenticatedDashboardAvailabilityRoute
  '/dashboard/bio': typeof AuthenticatedDashboardBioRoute
  '/dashboard/booking-flow': typeof AuthenticatedDashboardBookingFlowRoute
  '/dashboard/bookings': typeof AuthenticatedDashboardBookingsRoute
  '/dashboard/branding': typeof AuthenticatedDashboardBrandingRoute
  '/dashboard/categories': typeof AuthenticatedDashboardCategoriesRoute
  '/dashboard/clinic': typeof AuthenticatedDashboardClinicRoute
  '/dashboard/consent-forms': typeof AuthenticatedDashboardConsentFormsRoute
  '/dashboard/discounts': typeof AuthenticatedDashboardDiscountsRoute
  '/dashboard/locations': typeof AuthenticatedDashboardLocationsRoute
  '/dashboard/medical-forms': typeof AuthenticatedDashboardMedicalFormsRoute
  '/dashboard/menu': typeof AuthenticatedDashboardMenuRoute
  '/dashboard/model-slots': typeof AuthenticatedDashboardModelSlotsRoute
  '/dashboard/new-appointment': typeof AuthenticatedDashboardNewAppointmentRoute
  '/dashboard/packages': typeof AuthenticatedDashboardPackagesRoute
  '/dashboard/patients': typeof AuthenticatedDashboardPatientsRouteWithChildren
  '/dashboard/payments': typeof AuthenticatedDashboardPaymentsRoute
  '/dashboard/policies': typeof AuthenticatedDashboardPoliciesRoute
  '/dashboard/practitioners': typeof AuthenticatedDashboardPractitionersRoute
  '/dashboard/quiz': typeof AuthenticatedDashboardQuizRoute
  '/dashboard/reviews': typeof AuthenticatedDashboardReviewsRoute
  '/dashboard/services': typeof AuthenticatedDashboardServicesRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/dashboard/treatments': typeof AuthenticatedDashboardTreatmentsRoute
  '/m/$slug/about': typeof MSlugAboutRoute
  '/m/$slug/account': typeof MSlugAccountRoute
  '/m/$slug/auth': typeof MSlugAuthRoute
  '/m/$slug/book-multi': typeof MSlugBookMultiRoute
  '/m/$slug/quiz': typeof MSlugQuizRoute
  '/m/$slug/reviews': typeof MSlugReviewsRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/m/$slug/': typeof MSlugIndexRoute
  '/dashboard/consultations/$id': typeof AuthenticatedDashboardConsultationsIdRoute
  '/dashboard/patients/$id': typeof AuthenticatedDashboardPatientsIdRoute
  '/m/$slug/book/$treatmentId': typeof MSlugBookTreatmentIdRoute
  '/m/$slug/manage/$token': typeof MSlugManageTokenRoute
  '/dashboard/consultations/': typeof AuthenticatedDashboardConsultationsIndexRoute
  '/dashboard/patients/': typeof AuthenticatedDashboardPatientsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/features': typeof FeaturesRoute
  '/prescriber-hub': typeof PrescriberHubRoute
  '/who-its-for': typeof WhoItsForRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/book/$slug': typeof BookSlugRoute
  '/c/$token': typeof CTokenRoute
  '/f/$token': typeof FTokenRoute
  '/dashboard/addons': typeof AuthenticatedDashboardAddonsRoute
  '/dashboard/aftercare': typeof AuthenticatedDashboardAftercareRoute
  '/dashboard/ai-import': typeof AuthenticatedDashboardAiImportRoute
  '/dashboard/availability': typeof AuthenticatedDashboardAvailabilityRoute
  '/dashboard/bio': typeof AuthenticatedDashboardBioRoute
  '/dashboard/booking-flow': typeof AuthenticatedDashboardBookingFlowRoute
  '/dashboard/bookings': typeof AuthenticatedDashboardBookingsRoute
  '/dashboard/branding': typeof AuthenticatedDashboardBrandingRoute
  '/dashboard/categories': typeof AuthenticatedDashboardCategoriesRoute
  '/dashboard/clinic': typeof AuthenticatedDashboardClinicRoute
  '/dashboard/consent-forms': typeof AuthenticatedDashboardConsentFormsRoute
  '/dashboard/discounts': typeof AuthenticatedDashboardDiscountsRoute
  '/dashboard/locations': typeof AuthenticatedDashboardLocationsRoute
  '/dashboard/medical-forms': typeof AuthenticatedDashboardMedicalFormsRoute
  '/dashboard/menu': typeof AuthenticatedDashboardMenuRoute
  '/dashboard/model-slots': typeof AuthenticatedDashboardModelSlotsRoute
  '/dashboard/new-appointment': typeof AuthenticatedDashboardNewAppointmentRoute
  '/dashboard/packages': typeof AuthenticatedDashboardPackagesRoute
  '/dashboard/payments': typeof AuthenticatedDashboardPaymentsRoute
  '/dashboard/policies': typeof AuthenticatedDashboardPoliciesRoute
  '/dashboard/practitioners': typeof AuthenticatedDashboardPractitionersRoute
  '/dashboard/quiz': typeof AuthenticatedDashboardQuizRoute
  '/dashboard/reviews': typeof AuthenticatedDashboardReviewsRoute
  '/dashboard/services': typeof AuthenticatedDashboardServicesRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/dashboard/treatments': typeof AuthenticatedDashboardTreatmentsRoute
  '/m/$slug/about': typeof MSlugAboutRoute
  '/m/$slug/account': typeof MSlugAccountRoute
  '/m/$slug/auth': typeof MSlugAuthRoute
  '/m/$slug/book-multi': typeof MSlugBookMultiRoute
  '/m/$slug/quiz': typeof MSlugQuizRoute
  '/m/$slug/reviews': typeof MSlugReviewsRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/m/$slug': typeof MSlugIndexRoute
  '/dashboard/consultations/$id': typeof AuthenticatedDashboardConsultationsIdRoute
  '/dashboard/patients/$id': typeof AuthenticatedDashboardPatientsIdRoute
  '/m/$slug/book/$treatmentId': typeof MSlugBookTreatmentIdRoute
  '/m/$slug/manage/$token': typeof MSlugManageTokenRoute
  '/dashboard/consultations': typeof AuthenticatedDashboardConsultationsIndexRoute
  '/dashboard/patients': typeof AuthenticatedDashboardPatientsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/features': typeof FeaturesRoute
  '/prescriber-hub': typeof PrescriberHubRoute
  '/who-its-for': typeof WhoItsForRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/book/$slug': typeof BookSlugRoute
  '/c/$token': typeof CTokenRoute
  '/f/$token': typeof FTokenRoute
  '/m/$slug': typeof MSlugRouteWithChildren
  '/_authenticated/dashboard/addons': typeof AuthenticatedDashboardAddonsRoute
  '/_authenticated/dashboard/aftercare': typeof AuthenticatedDashboardAftercareRoute
  '/_authenticated/dashboard/ai-import': typeof AuthenticatedDashboardAiImportRoute
  '/_authenticated/dashboard/availability': typeof AuthenticatedDashboardAvailabilityRoute
  '/_authenticated/dashboard/bio': typeof AuthenticatedDashboardBioRoute
  '/_authenticated/dashboard/booking-flow': typeof AuthenticatedDashboardBookingFlowRoute
  '/_authenticated/dashboard/bookings': typeof AuthenticatedDashboardBookingsRoute
  '/_authenticated/dashboard/branding': typeof AuthenticatedDashboardBrandingRoute
  '/_authenticated/dashboard/categories': typeof AuthenticatedDashboardCategoriesRoute
  '/_authenticated/dashboard/clinic': typeof AuthenticatedDashboardClinicRoute
  '/_authenticated/dashboard/consent-forms': typeof AuthenticatedDashboardConsentFormsRoute
  '/_authenticated/dashboard/discounts': typeof AuthenticatedDashboardDiscountsRoute
  '/_authenticated/dashboard/locations': typeof AuthenticatedDashboardLocationsRoute
  '/_authenticated/dashboard/medical-forms': typeof AuthenticatedDashboardMedicalFormsRoute
  '/_authenticated/dashboard/menu': typeof AuthenticatedDashboardMenuRoute
  '/_authenticated/dashboard/model-slots': typeof AuthenticatedDashboardModelSlotsRoute
  '/_authenticated/dashboard/new-appointment': typeof AuthenticatedDashboardNewAppointmentRoute
  '/_authenticated/dashboard/packages': typeof AuthenticatedDashboardPackagesRoute
  '/_authenticated/dashboard/patients': typeof AuthenticatedDashboardPatientsRouteWithChildren
  '/_authenticated/dashboard/payments': typeof AuthenticatedDashboardPaymentsRoute
  '/_authenticated/dashboard/policies': typeof AuthenticatedDashboardPoliciesRoute
  '/_authenticated/dashboard/practitioners': typeof AuthenticatedDashboardPractitionersRoute
  '/_authenticated/dashboard/quiz': typeof AuthenticatedDashboardQuizRoute
  '/_authenticated/dashboard/reviews': typeof AuthenticatedDashboardReviewsRoute
  '/_authenticated/dashboard/services': typeof AuthenticatedDashboardServicesRoute
  '/_authenticated/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/_authenticated/dashboard/treatments': typeof AuthenticatedDashboardTreatmentsRoute
  '/m/$slug/about': typeof MSlugAboutRoute
  '/m/$slug/account': typeof MSlugAccountRoute
  '/m/$slug/auth': typeof MSlugAuthRoute
  '/m/$slug/book-multi': typeof MSlugBookMultiRoute
  '/m/$slug/quiz': typeof MSlugQuizRoute
  '/m/$slug/reviews': typeof MSlugReviewsRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/m/$slug/': typeof MSlugIndexRoute
  '/_authenticated/dashboard/consultations/$id': typeof AuthenticatedDashboardConsultationsIdRoute
  '/_authenticated/dashboard/patients/$id': typeof AuthenticatedDashboardPatientsIdRoute
  '/m/$slug/book/$treatmentId': typeof MSlugBookTreatmentIdRoute
  '/m/$slug/manage/$token': typeof MSlugManageTokenRoute
  '/_authenticated/dashboard/consultations/': typeof AuthenticatedDashboardConsultationsIndexRoute
  '/_authenticated/dashboard/patients/': typeof AuthenticatedDashboardPatientsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/features'
    | '/prescriber-hub'
    | '/who-its-for'
    | '/admin'
    | '/dashboard'
    | '/onboarding'
    | '/book/$slug'
    | '/c/$token'
    | '/f/$token'
    | '/m/$slug'
    | '/dashboard/addons'
    | '/dashboard/aftercare'
    | '/dashboard/ai-import'
    | '/dashboard/availability'
    | '/dashboard/bio'
    | '/dashboard/booking-flow'
    | '/dashboard/bookings'
    | '/dashboard/branding'
    | '/dashboard/categories'
    | '/dashboard/clinic'
    | '/dashboard/consent-forms'
    | '/dashboard/discounts'
    | '/dashboard/locations'
    | '/dashboard/medical-forms'
    | '/dashboard/menu'
    | '/dashboard/model-slots'
    | '/dashboard/new-appointment'
    | '/dashboard/packages'
    | '/dashboard/patients'
    | '/dashboard/payments'
    | '/dashboard/policies'
    | '/dashboard/practitioners'
    | '/dashboard/quiz'
    | '/dashboard/reviews'
    | '/dashboard/services'
    | '/dashboard/settings'
    | '/dashboard/treatments'
    | '/m/$slug/about'
    | '/m/$slug/account'
    | '/m/$slug/auth'
    | '/m/$slug/book-multi'
    | '/m/$slug/quiz'
    | '/m/$slug/reviews'
    | '/dashboard/'
    | '/m/$slug/'
    | '/dashboard/consultations/$id'
    | '/dashboard/patients/$id'
    | '/m/$slug/book/$treatmentId'
    | '/m/$slug/manage/$token'
    | '/dashboard/consultations/'
    | '/dashboard/patients/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/features'
    | '/prescriber-hub'
    | '/who-its-for'
    | '/admin'
    | '/onboarding'
    | '/book/$slug'
    | '/c/$token'
    | '/f/$token'
    | '/dashboard/addons'
    | '/dashboard/aftercare'
    | '/dashboard/ai-import'
    | '/dashboard/availability'
    | '/dashboard/bio'
    | '/dashboard/booking-flow'
    | '/dashboard/bookings'
    | '/dashboard/branding'
    | '/dashboard/categories'
    | '/dashboard/clinic'
    | '/dashboard/consent-forms'
    | '/dashboard/discounts'
    | '/dashboard/locations'
    | '/dashboard/medical-forms'
    | '/dashboard/menu'
    | '/dashboard/model-slots'
    | '/dashboard/new-appointment'
    | '/dashboard/packages'
    | '/dashboard/payments'
    | '/dashboard/policies'
    | '/dashboard/practitioners'
    | '/dashboard/quiz'
    | '/dashboard/reviews'
    | '/dashboard/services'
    | '/dashboard/settings'
    | '/dashboard/treatments'
    | '/m/$slug/about'
    | '/m/$slug/account'
    | '/m/$slug/auth'
    | '/m/$slug/book-multi'
    | '/m/$slug/quiz'
    | '/m/$slug/reviews'
    | '/dashboard'
    | '/m/$slug'
    | '/dashboard/consultations/$id'
    | '/dashboard/patients/$id'
    | '/m/$slug/book/$treatmentId'
    | '/m/$slug/manage/$token'
    | '/dashboard/consultations'
    | '/dashboard/patients'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/features'
    | '/prescriber-hub'
    | '/who-its-for'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/onboarding'
    | '/book/$slug'
    | '/c/$token'
    | '/f/$token'
    | '/m/$slug'
    | '/_authenticated/dashboard/addons'
    | '/_authenticated/dashboard/aftercare'
    | '/_authenticated/dashboard/ai-import'
    | '/_authenticated/dashboard/availability'
    | '/_authenticated/dashboard/bio'
    | '/_authenticated/dashboard/booking-flow'
    | '/_authenticated/dashboard/bookings'
    | '/_authenticated/dashboard/branding'
    | '/_authenticated/dashboard/categories'
    | '/_authenticated/dashboard/clinic'
    | '/_authenticated/dashboard/consent-forms'
    | '/_authenticated/dashboard/discounts'
    | '/_authenticated/dashboard/locations'
    | '/_authenticated/dashboard/medical-forms'
    | '/_authenticated/dashboard/menu'
    | '/_authenticated/dashboard/model-slots'
    | '/_authenticated/dashboard/new-appointment'
    | '/_authenticated/dashboard/packages'
    | '/_authenticated/dashboard/patients'
    | '/_authenticated/dashboard/payments'
    | '/_authenticated/dashboard/policies'
    | '/_authenticated/dashboard/practitioners'
    | '/_authenticated/dashboard/quiz'
    | '/_authenticated/dashboard/reviews'
    | '/_authenticated/dashboard/services'
    | '/_authenticated/dashboard/settings'
    | '/_authenticated/dashboard/treatments'
    | '/m/$slug/about'
    | '/m/$slug/account'
    | '/m/$slug/auth'
    | '/m/$slug/book-multi'
    | '/m/$slug/quiz'
    | '/m/$slug/reviews'
    | '/_authenticated/dashboard/'
    | '/m/$slug/'
    | '/_authenticated/dashboard/consultations/$id'
    | '/_authenticated/dashboard/patients/$id'
    | '/m/$slug/book/$treatmentId'
    | '/m/$slug/manage/$token'
    | '/_authenticated/dashboard/consultations/'
    | '/_authenticated/dashboard/patients/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  FeaturesRoute: typeof FeaturesRoute
  PrescriberHubRoute: typeof PrescriberHubRoute
  WhoItsForRoute: typeof WhoItsForRoute
  BookSlugRoute: typeof BookSlugRoute
  CTokenRoute: typeof CTokenRoute
  FTokenRoute: typeof FTokenRoute
  MSlugRoute: typeof MSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/who-its-for': {
      id: '/who-its-for'
      path: '/who-its-for'
      fullPath: '/who-its-for'
      preLoaderRoute: typeof WhoItsForRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prescriber-hub': {
      id: '/prescriber-hub'
      path: '/prescriber-hub'
      fullPath: '/prescriber-hub'
      preLoaderRoute: typeof PrescriberHubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/$slug': {
      id: '/m/$slug'
      path: '/m/$slug'
      fullPath: '/m/$slug'
      preLoaderRoute: typeof MSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/f/$token': {
      id: '/f/$token'
      path: '/f/$token'
      fullPath: '/f/$token'
      preLoaderRoute: typeof FTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$token': {
      id: '/c/$token'
      path: '/c/$token'
      fullPath: '/c/$token'
      preLoaderRoute: typeof CTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$slug': {
      id: '/book/$slug'
      path: '/book/$slug'
      fullPath: '/book/$slug'
      preLoaderRoute: typeof BookSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/m/$slug/': {
      id: '/m/$slug/'
      path: '/'
      fullPath: '/m/$slug/'
      preLoaderRoute: typeof MSlugIndexRouteImport
      parentRoute: typeof MSlugRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/m/$slug/reviews': {
      id: '/m/$slug/reviews'
      path: '/reviews'
      fullPath: '/m/$slug/reviews'
      preLoaderRoute: typeof MSlugReviewsRouteImport
      parentRoute: typeof MSlugRoute
    }
    '/m/$slug/quiz': {
      id: '/m/$slug/quiz'
      path: '/quiz'
      fullPath: '/m/$slug/quiz'
      preLoaderRoute: typeof MSlugQuizRouteImport
      parentRoute: typeof MSlugRoute
    }
    '/m/$slug/book-multi': {
      id: '/m/$slug/book-multi'
      path: '/book-multi'
      fullPath: '/m/$slug/book-multi'
      preLoaderRoute: typeof MSlugBookMultiRouteImport
      parentRoute: typeof MSlugRoute
    }
    '/m/$slug/auth': {
      id: '/m/$slug/auth'
      path: '/auth'
      fullPath: '/m/$slug/auth'
      preLoaderRoute: typeof MSlugAuthRouteImport
      parentRoute: typeof MSlugRoute
    }
    '/m/$slug/account': {
      id: '/m/$slug/account'
      path: '/account'
      fullPath: '/m/$slug/account'
      preLoaderRoute: typeof MSlugAccountRouteImport
      parentRoute: typeof MSlugRoute
    }
    '/m/$slug/about': {
      id: '/m/$slug/about'
      path: '/about'
      fullPath: '/m/$slug/about'
      preLoaderRoute: typeof MSlugAboutRouteImport
      parentRoute: typeof MSlugRoute
    }
    '/_authenticated/dashboard/treatments': {
      id: '/_authenticated/dashboard/treatments'
      path: '/treatments'
      fullPath: '/dashboard/treatments'
      preLoaderRoute: typeof AuthenticatedDashboardTreatmentsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/settings': {
      id: '/_authenticated/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AuthenticatedDashboardSettingsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/services': {
      id: '/_authenticated/dashboard/services'
      path: '/services'
      fullPath: '/dashboard/services'
      preLoaderRoute: typeof AuthenticatedDashboardServicesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/reviews': {
      id: '/_authenticated/dashboard/reviews'
      path: '/reviews'
      fullPath: '/dashboard/reviews'
      preLoaderRoute: typeof AuthenticatedDashboardReviewsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/quiz': {
      id: '/_authenticated/dashboard/quiz'
      path: '/quiz'
      fullPath: '/dashboard/quiz'
      preLoaderRoute: typeof AuthenticatedDashboardQuizRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/practitioners': {
      id: '/_authenticated/dashboard/practitioners'
      path: '/practitioners'
      fullPath: '/dashboard/practitioners'
      preLoaderRoute: typeof AuthenticatedDashboardPractitionersRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/policies': {
      id: '/_authenticated/dashboard/policies'
      path: '/policies'
      fullPath: '/dashboard/policies'
      preLoaderRoute: typeof AuthenticatedDashboardPoliciesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/payments': {
      id: '/_authenticated/dashboard/payments'
      path: '/payments'
      fullPath: '/dashboard/payments'
      preLoaderRoute: typeof AuthenticatedDashboardPaymentsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/patients': {
      id: '/_authenticated/dashboard/patients'
      path: '/patients'
      fullPath: '/dashboard/patients'
      preLoaderRoute: typeof AuthenticatedDashboardPatientsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/packages': {
      id: '/_authenticated/dashboard/packages'
      path: '/packages'
      fullPath: '/dashboard/packages'
      preLoaderRoute: typeof AuthenticatedDashboardPackagesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/new-appointment': {
      id: '/_authenticated/dashboard/new-appointment'
      path: '/new-appointment'
      fullPath: '/dashboard/new-appointment'
      preLoaderRoute: typeof AuthenticatedDashboardNewAppointmentRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/model-slots': {
      id: '/_authenticated/dashboard/model-slots'
      path: '/model-slots'
      fullPath: '/dashboard/model-slots'
      preLoaderRoute: typeof AuthenticatedDashboardModelSlotsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/menu': {
      id: '/_authenticated/dashboard/menu'
      path: '/menu'
      fullPath: '/dashboard/menu'
      preLoaderRoute: typeof AuthenticatedDashboardMenuRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/medical-forms': {
      id: '/_authenticated/dashboard/medical-forms'
      path: '/medical-forms'
      fullPath: '/dashboard/medical-forms'
      preLoaderRoute: typeof AuthenticatedDashboardMedicalFormsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/locations': {
      id: '/_authenticated/dashboard/locations'
      path: '/locations'
      fullPath: '/dashboard/locations'
      preLoaderRoute: typeof AuthenticatedDashboardLocationsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/discounts': {
      id: '/_authenticated/dashboard/discounts'
      path: '/discounts'
      fullPath: '/dashboard/discounts'
      preLoaderRoute: typeof AuthenticatedDashboardDiscountsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/consent-forms': {
      id: '/_authenticated/dashboard/consent-forms'
      path: '/consent-forms'
      fullPath: '/dashboard/consent-forms'
      preLoaderRoute: typeof AuthenticatedDashboardConsentFormsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/clinic': {
      id: '/_authenticated/dashboard/clinic'
      path: '/clinic'
      fullPath: '/dashboard/clinic'
      preLoaderRoute: typeof AuthenticatedDashboardClinicRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/categories': {
      id: '/_authenticated/dashboard/categories'
      path: '/categories'
      fullPath: '/dashboard/categories'
      preLoaderRoute: typeof AuthenticatedDashboardCategoriesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/branding': {
      id: '/_authenticated/dashboard/branding'
      path: '/branding'
      fullPath: '/dashboard/branding'
      preLoaderRoute: typeof AuthenticatedDashboardBrandingRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/bookings': {
      id: '/_authenticated/dashboard/bookings'
      path: '/bookings'
      fullPath: '/dashboard/bookings'
      preLoaderRoute: typeof AuthenticatedDashboardBookingsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/booking-flow': {
      id: '/_authenticated/dashboard/booking-flow'
      path: '/booking-flow'
      fullPath: '/dashboard/booking-flow'
      preLoaderRoute: typeof AuthenticatedDashboardBookingFlowRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/bio': {
      id: '/_authenticated/dashboard/bio'
      path: '/bio'
      fullPath: '/dashboard/bio'
      preLoaderRoute: typeof AuthenticatedDashboardBioRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/availability': {
      id: '/_authenticated/dashboard/availability'
      path: '/availability'
      fullPath: '/dashboard/availability'
      preLoaderRoute: typeof AuthenticatedDashboardAvailabilityRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/ai-import': {
      id: '/_authenticated/dashboard/ai-import'
      path: '/ai-import'
      fullPath: '/dashboard/ai-import'
      preLoaderRoute: typeof AuthenticatedDashboardAiImportRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/aftercare': {
      id: '/_authenticated/dashboard/aftercare'
      path: '/aftercare'
      fullPath: '/dashboard/aftercare'
      preLoaderRoute: typeof AuthenticatedDashboardAftercareRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/addons': {
      id: '/_authenticated/dashboard/addons'
      path: '/addons'
      fullPath: '/dashboard/addons'
      preLoaderRoute: typeof AuthenticatedDashboardAddonsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/patients/': {
      id: '/_authenticated/dashboard/patients/'
      path: '/'
      fullPath: '/dashboard/patients/'
      preLoaderRoute: typeof AuthenticatedDashboardPatientsIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardPatientsRoute
    }
    '/_authenticated/dashboard/consultations/': {
      id: '/_authenticated/dashboard/consultations/'
      path: '/consultations'
      fullPath: '/dashboard/consultations/'
      preLoaderRoute: typeof AuthenticatedDashboardConsultationsIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/m/$slug/manage/$token': {
      id: '/m/$slug/manage/$token'
      path: '/manage/$token'
      fullPath: '/m/$slug/manage/$token'
      preLoaderRoute: typeof MSlugManageTokenRouteImport
      parentRoute: typeof MSlugRoute
    }
    '/m/$slug/book/$treatmentId': {
      id: '/m/$slug/book/$treatmentId'
      path: '/book/$treatmentId'
      fullPath: '/m/$slug/book/$treatmentId'
      preLoaderRoute: typeof MSlugBookTreatmentIdRouteImport
      parentRoute: typeof MSlugRoute
    }
    '/_authenticated/dashboard/patients/$id': {
      id: '/_authenticated/dashboard/patients/$id'
      path: '/$id'
      fullPath: '/dashboard/patients/$id'
      preLoaderRoute: typeof AuthenticatedDashboardPatientsIdRouteImport
      parentRoute: typeof AuthenticatedDashboardPatientsRoute
    }
    '/_authenticated/dashboard/consultations/$id': {
      id: '/_authenticated/dashboard/consultations/$id'
      path: '/consultations/$id'
      fullPath: '/dashboard/consultations/$id'
      preLoaderRoute: typeof AuthenticatedDashboardConsultationsIdRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
  }
}

interface AuthenticatedDashboardPatientsRouteChildren {
  AuthenticatedDashboardPatientsIdRoute: typeof AuthenticatedDashboardPatientsIdRoute
  AuthenticatedDashboardPatientsIndexRoute: typeof AuthenticatedDashboardPatientsIndexRoute
}

const AuthenticatedDashboardPatientsRouteChildren: AuthenticatedDashboardPatientsRouteChildren =
  {
    AuthenticatedDashboardPatientsIdRoute:
      AuthenticatedDashboardPatientsIdRoute,
    AuthenticatedDashboardPatientsIndexRoute:
      AuthenticatedDashboardPatientsIndexRoute,
  }

const AuthenticatedDashboardPatientsRouteWithChildren =
  AuthenticatedDashboardPatientsRoute._addFileChildren(
    AuthenticatedDashboardPatientsRouteChildren,
  )

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardAddonsRoute: typeof AuthenticatedDashboardAddonsRoute
  AuthenticatedDashboardAftercareRoute: typeof AuthenticatedDashboardAftercareRoute
  AuthenticatedDashboardAiImportRoute: typeof AuthenticatedDashboardAiImportRoute
  AuthenticatedDashboardAvailabilityRoute: typeof AuthenticatedDashboardAvailabilityRoute
  AuthenticatedDashboardBioRoute: typeof AuthenticatedDashboardBioRoute
  AuthenticatedDashboardBookingFlowRoute: typeof AuthenticatedDashboardBookingFlowRoute
  AuthenticatedDashboardBookingsRoute: typeof AuthenticatedDashboardBookingsRoute
  AuthenticatedDashboardBrandingRoute: typeof AuthenticatedDashboardBrandingRoute
  AuthenticatedDashboardCategoriesRoute: typeof AuthenticatedDashboardCategoriesRoute
  AuthenticatedDashboardClinicRoute: typeof AuthenticatedDashboardClinicRoute
  AuthenticatedDashboardConsentFormsRoute: typeof AuthenticatedDashboardConsentFormsRoute
  AuthenticatedDashboardDiscountsRoute: typeof AuthenticatedDashboardDiscountsRoute
  AuthenticatedDashboardLocationsRoute: typeof AuthenticatedDashboardLocationsRoute
  AuthenticatedDashboardMedicalFormsRoute: typeof AuthenticatedDashboardMedicalFormsRoute
  AuthenticatedDashboardMenuRoute: typeof AuthenticatedDashboardMenuRoute
  AuthenticatedDashboardModelSlotsRoute: typeof AuthenticatedDashboardModelSlotsRoute
  AuthenticatedDashboardNewAppointmentRoute: typeof AuthenticatedDashboardNewAppointmentRoute
  AuthenticatedDashboardPackagesRoute: typeof AuthenticatedDashboardPackagesRoute
  AuthenticatedDashboardPatientsRoute: typeof AuthenticatedDashboardPatientsRouteWithChildren
  AuthenticatedDashboardPaymentsRoute: typeof AuthenticatedDashboardPaymentsRoute
  AuthenticatedDashboardPoliciesRoute: typeof AuthenticatedDashboardPoliciesRoute
  AuthenticatedDashboardPractitionersRoute: typeof AuthenticatedDashboardPractitionersRoute
  AuthenticatedDashboardQuizRoute: typeof AuthenticatedDashboardQuizRoute
  AuthenticatedDashboardReviewsRoute: typeof AuthenticatedDashboardReviewsRoute
  AuthenticatedDashboardServicesRoute: typeof AuthenticatedDashboardServicesRoute
  AuthenticatedDashboardSettingsRoute: typeof AuthenticatedDashboardSettingsRoute
  AuthenticatedDashboardTreatmentsRoute: typeof AuthenticatedDashboardTreatmentsRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedDashboardConsultationsIdRoute: typeof AuthenticatedDashboardConsultationsIdRoute
  AuthenticatedDashboardConsultationsIndexRoute: typeof AuthenticatedDashboardConsultationsIndexRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardAddonsRoute: AuthenticatedDashboardAddonsRoute,
    AuthenticatedDashboardAftercareRoute: AuthenticatedDashboardAftercareRoute,
    AuthenticatedDashboardAiImportRoute: AuthenticatedDashboardAiImportRoute,
    AuthenticatedDashboardAvailabilityRoute:
      AuthenticatedDashboardAvailabilityRoute,
    AuthenticatedDashboardBioRoute: AuthenticatedDashboardBioRoute,
    AuthenticatedDashboardBookingFlowRoute:
      AuthenticatedDashboardBookingFlowRoute,
    AuthenticatedDashboardBookingsRoute: AuthenticatedDashboardBookingsRoute,
    AuthenticatedDashboardBrandingRoute: AuthenticatedDashboardBrandingRoute,
    AuthenticatedDashboardCategoriesRoute:
      AuthenticatedDashboardCategoriesRoute,
    AuthenticatedDashboardClinicRoute: AuthenticatedDashboardClinicRoute,
    AuthenticatedDashboardConsentFormsRoute:
      AuthenticatedDashboardConsentFormsRoute,
    AuthenticatedDashboardDiscountsRoute: AuthenticatedDashboardDiscountsRoute,
    AuthenticatedDashboardLocationsRoute: AuthenticatedDashboardLocationsRoute,
    AuthenticatedDashboardMedicalFormsRoute:
      AuthenticatedDashboardMedicalFormsRoute,
    AuthenticatedDashboardMenuRoute: AuthenticatedDashboardMenuRoute,
    AuthenticatedDashboardModelSlotsRoute:
      AuthenticatedDashboardModelSlotsRoute,
    AuthenticatedDashboardNewAppointmentRoute:
      AuthenticatedDashboardNewAppointmentRoute,
    AuthenticatedDashboardPackagesRoute: AuthenticatedDashboardPackagesRoute,
    AuthenticatedDashboardPatientsRoute:
      AuthenticatedDashboardPatientsRouteWithChildren,
    AuthenticatedDashboardPaymentsRoute: AuthenticatedDashboardPaymentsRoute,
    AuthenticatedDashboardPoliciesRoute: AuthenticatedDashboardPoliciesRoute,
    AuthenticatedDashboardPractitionersRoute:
      AuthenticatedDashboardPractitionersRoute,
    AuthenticatedDashboardQuizRoute: AuthenticatedDashboardQuizRoute,
    AuthenticatedDashboardReviewsRoute: AuthenticatedDashboardReviewsRoute,
    AuthenticatedDashboardServicesRoute: AuthenticatedDashboardServicesRoute,
    AuthenticatedDashboardSettingsRoute: AuthenticatedDashboardSettingsRoute,
    AuthenticatedDashboardTreatmentsRoute:
      AuthenticatedDashboardTreatmentsRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
    AuthenticatedDashboardConsultationsIdRoute:
      AuthenticatedDashboardConsultationsIdRoute,
    AuthenticatedDashboardConsultationsIndexRoute:
      AuthenticatedDashboardConsultationsIndexRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface MSlugRouteChildren {
  MSlugAboutRoute: typeof MSlugAboutRoute
  MSlugAccountRoute: typeof MSlugAccountRoute
  MSlugAuthRoute: typeof MSlugAuthRoute
  MSlugBookMultiRoute: typeof MSlugBookMultiRoute
  MSlugQuizRoute: typeof MSlugQuizRoute
  MSlugReviewsRoute: typeof MSlugReviewsRoute
  MSlugIndexRoute: typeof MSlugIndexRoute
  MSlugBookTreatmentIdRoute: typeof MSlugBookTreatmentIdRoute
  MSlugManageTokenRoute: typeof MSlugManageTokenRoute
}

const MSlugRouteChildren: MSlugRouteChildren = {
  MSlugAboutRoute: MSlugAboutRoute,
  MSlugAccountRoute: MSlugAccountRoute,
  MSlugAuthRoute: MSlugAuthRoute,
  MSlugBookMultiRoute: MSlugBookMultiRoute,
  MSlugQuizRoute: MSlugQuizRoute,
  MSlugReviewsRoute: MSlugReviewsRoute,
  MSlugIndexRoute: MSlugIndexRoute,
  MSlugBookTreatmentIdRoute: MSlugBookTreatmentIdRoute,
  MSlugManageTokenRoute: MSlugManageTokenRoute,
}

const MSlugRouteWithChildren = MSlugRoute._addFileChildren(MSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  FeaturesRoute: FeaturesRoute,
  PrescriberHubRoute: PrescriberHubRoute,
  WhoItsForRoute: WhoItsForRoute,
  BookSlugRoute: BookSlugRoute,
  CTokenRoute: CTokenRoute,
  FTokenRoute: FTokenRoute,
  MSlugRoute: MSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
