/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MSlugRouteImport } from './routes/m.$slug'
import { Route as BookSlugRouteImport } from './routes/book.$slug'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as MSlugIndexRouteImport } from './routes/m.$slug.index'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as MSlugReviewsRouteImport } from './routes/m.$slug.reviews'
import { Route as MSlugAuthRouteImport } from './routes/m.$slug.auth'
import { Route as MSlugAccountRouteImport } from './routes/m.$slug.account'
import { Route as MSlugAboutRouteImport } from './routes/m.$slug.about'
import { Route as AuthenticatedDashboardTreatmentsRouteImport } from './routes/_authenticated/dashboard.treatments'
import { Route as AuthenticatedDashboardReviewsRouteImport } from './routes/_authenticated/dashboard.reviews'
import { Route as AuthenticatedDashboardPaymentsRouteImport } from './routes/_authenticated/dashboard.payments'
import { Route as AuthenticatedDashboardMedicalFormsRouteImport } from './routes/_authenticated/dashboard.medical-forms'
import { Route as AuthenticatedDashboardLocationsRouteImport } from './routes/_authenticated/dashboard.locations'
import { Route as AuthenticatedDashboardConsentFormsRouteImport } from './routes/_authenticated/dashboard.consent-forms'
import { Route as AuthenticatedDashboardClinicRouteImport } from './routes/_authenticated/dashboard.clinic'
import { Route as AuthenticatedDashboardCategoriesRouteImport } from './routes/_authenticated/dashboard.categories'
import { Route as AuthenticatedDashboardBrandingRouteImport } from './routes/_authenticated/dashboard.branding'
import { Route as AuthenticatedDashboardBookingsRouteImport } from './routes/_authenticated/dashboard.bookings'
import { Route as AuthenticatedDashboardBioRouteImport } from './routes/_authenticated/dashboard.bio'
import { Route as AuthenticatedDashboardAvailabilityRouteImport } from './routes/_authenticated/dashboard.availability'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MSlugRoute = MSlugRouteImport.update({
  id: '/m/$slug',
  path: '/m/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BookSlugRoute = BookSlugRouteImport.update({
  id: '/book/$slug',
  path: '/book/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const MSlugIndexRoute = MSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MSlugRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const MSlugReviewsRoute = MSlugReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => MSlugRoute,
} as any)
const MSlugAuthRoute = MSlugAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => MSlugRoute,
} as any)
const MSlugAccountRoute = MSlugAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => MSlugRoute,
} as any)
const MSlugAboutRoute = MSlugAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => MSlugRoute,
} as any)
const AuthenticatedDashboardTreatmentsRoute =
  AuthenticatedDashboardTreatmentsRouteImport.update({
    id: '/treatments',
    path: '/treatments',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardReviewsRoute =
  AuthenticatedDashboardReviewsRouteImport.update({
    id: '/reviews',
    path: '/reviews',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardPaymentsRoute =
  AuthenticatedDashboardPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardMedicalFormsRoute =
  AuthenticatedDashboardMedicalFormsRouteImport.update({
    id: '/medical-forms',
    path: '/medical-forms',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardLocationsRoute =
  AuthenticatedDashboardLocationsRouteImport.update({
    id: '/locations',
    path: '/locations',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardConsentFormsRoute =
  AuthenticatedDashboardConsentFormsRouteImport.update({
    id: '/consent-forms',
    path: '/consent-forms',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardClinicRoute =
  AuthenticatedDashboardClinicRouteImport.update({
    id: '/clinic',
    path: '/clinic',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardCategoriesRoute =
  AuthenticatedDashboardCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardBrandingRoute =
  AuthenticatedDashboardBrandingRouteImport.update({
    id: '/branding',
    path: '/branding',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardBookingsRoute =
  AuthenticatedDashboardBookingsRouteImport.update({
    id: '/bookings',
    path: '/bookings',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardBioRoute =
  AuthenticatedDashboardBioRouteImport.update({
    id: '/bio',
    path: '/bio',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAvailabilityRoute =
  AuthenticatedDashboardAvailabilityRouteImport.update({
    id: '/availability',
    path: '/availability',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/book/$slug': typeof BookSlugRoute
  '/m/$slug': typeof MSlugRouteWithChildren
  '/dashboard/availability': typeof AuthenticatedDashboardAvailabilityRoute
  '/dashboard/bio': typeof AuthenticatedDashboardBioRoute
  '/dashboard/bookings': typeof AuthenticatedDashboardBookingsRoute
  '/dashboard/branding': typeof AuthenticatedDashboardBrandingRoute
  '/dashboard/categories': typeof AuthenticatedDashboardCategoriesRoute
  '/dashboard/clinic': typeof AuthenticatedDashboardClinicRoute
  '/dashboard/consent-forms': typeof AuthenticatedDashboardConsentFormsRoute
  '/dashboard/locations': typeof AuthenticatedDashboardLocationsRoute
  '/dashboard/medical-forms': typeof AuthenticatedDashboardMedicalFormsRoute
  '/dashboard/payments': typeof AuthenticatedDashboardPaymentsRoute
  '/dashboard/reviews': typeof AuthenticatedDashboardReviewsRoute
  '/dashboard/treatments': typeof AuthenticatedDashboardTreatmentsRoute
  '/m/$slug/about': typeof MSlugAboutRoute
  '/m/$slug/account': typeof MSlugAccountRoute
  '/m/$slug/auth': typeof MSlugAuthRoute
  '/m/$slug/reviews': typeof MSlugReviewsRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/m/$slug/': typeof MSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/book/$slug': typeof BookSlugRoute
  '/dashboard/availability': typeof AuthenticatedDashboardAvailabilityRoute
  '/dashboard/bio': typeof AuthenticatedDashboardBioRoute
  '/dashboard/bookings': typeof AuthenticatedDashboardBookingsRoute
  '/dashboard/branding': typeof AuthenticatedDashboardBrandingRoute
  '/dashboard/categories': typeof AuthenticatedDashboardCategoriesRoute
  '/dashboard/clinic': typeof AuthenticatedDashboardClinicRoute
  '/dashboard/consent-forms': typeof AuthenticatedDashboardConsentFormsRoute
  '/dashboard/locations': typeof AuthenticatedDashboardLocationsRoute
  '/dashboard/medical-forms': typeof AuthenticatedDashboardMedicalFormsRoute
  '/dashboard/payments': typeof AuthenticatedDashboardPaymentsRoute
  '/dashboard/reviews': typeof AuthenticatedDashboardReviewsRoute
  '/dashboard/treatments': typeof AuthenticatedDashboardTreatmentsRoute
  '/m/$slug/about': typeof MSlugAboutRoute
  '/m/$slug/account': typeof MSlugAccountRoute
  '/m/$slug/auth': typeof MSlugAuthRoute
  '/m/$slug/reviews': typeof MSlugReviewsRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/m/$slug': typeof MSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/book/$slug': typeof BookSlugRoute
  '/m/$slug': typeof MSlugRouteWithChildren
  '/_authenticated/dashboard/availability': typeof AuthenticatedDashboardAvailabilityRoute
  '/_authenticated/dashboard/bio': typeof AuthenticatedDashboardBioRoute
  '/_authenticated/dashboard/bookings': typeof AuthenticatedDashboardBookingsRoute
  '/_authenticated/dashboard/branding': typeof AuthenticatedDashboardBrandingRoute
  '/_authenticated/dashboard/categories': typeof AuthenticatedDashboardCategoriesRoute
  '/_authenticated/dashboard/clinic': typeof AuthenticatedDashboardClinicRoute
  '/_authenticated/dashboard/consent-forms': typeof AuthenticatedDashboardConsentFormsRoute
  '/_authenticated/dashboard/locations': typeof AuthenticatedDashboardLocationsRoute
  '/_authenticated/dashboard/medical-forms': typeof AuthenticatedDashboardMedicalFormsRoute
  '/_authenticated/dashboard/payments': typeof AuthenticatedDashboardPaymentsRoute
  '/_authenticated/dashboard/reviews': typeof AuthenticatedDashboardReviewsRoute
  '/_authenticated/dashboard/treatments': typeof AuthenticatedDashboardTreatmentsRoute
  '/m/$slug/about': typeof MSlugAboutRoute
  '/m/$slug/account': typeof MSlugAccountRoute
  '/m/$slug/auth': typeof MSlugAuthRoute
  '/m/$slug/reviews': typeof MSlugReviewsRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/m/$slug/': typeof MSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/onboarding'
    | '/book/$slug'
    | '/m/$slug'
    | '/dashboard/availability'
    | '/dashboard/bio'
    | '/dashboard/bookings'
    | '/dashboard/branding'
    | '/dashboard/categories'
    | '/dashboard/clinic'
    | '/dashboard/consent-forms'
    | '/dashboard/locations'
    | '/dashboard/medical-forms'
    | '/dashboard/payments'
    | '/dashboard/reviews'
    | '/dashboard/treatments'
    | '/m/$slug/about'
    | '/m/$slug/account'
    | '/m/$slug/auth'
    | '/m/$slug/reviews'
    | '/dashboard/'
    | '/m/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/book/$slug'
    | '/dashboard/availability'
    | '/dashboard/bio'
    | '/dashboard/bookings'
    | '/dashboard/branding'
    | '/dashboard/categories'
    | '/dashboard/clinic'
    | '/dashboard/consent-forms'
    | '/dashboard/locations'
    | '/dashboard/medical-forms'
    | '/dashboard/payments'
    | '/dashboard/reviews'
    | '/dashboard/treatments'
    | '/m/$slug/about'
    | '/m/$slug/account'
    | '/m/$slug/auth'
    | '/m/$slug/reviews'
    | '/dashboard'
    | '/m/$slug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/onboarding'
    | '/book/$slug'
    | '/m/$slug'
    | '/_authenticated/dashboard/availability'
    | '/_authenticated/dashboard/bio'
    | '/_authenticated/dashboard/bookings'
    | '/_authenticated/dashboard/branding'
    | '/_authenticated/dashboard/categories'
    | '/_authenticated/dashboard/clinic'
    | '/_authenticated/dashboard/consent-forms'
    | '/_authenticated/dashboard/locations'
    | '/_authenticated/dashboard/medical-forms'
    | '/_authenticated/dashboard/payments'
    | '/_authenticated/dashboard/reviews'
    | '/_authenticated/dashboard/treatments'
    | '/m/$slug/about'
    | '/m/$slug/account'
    | '/m/$slug/auth'
    | '/m/$slug/reviews'
    | '/_authenticated/dashboard/'
    | '/m/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  BookSlugRoute: typeof BookSlugRoute
  MSlugRoute: typeof MSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/$slug': {
      id: '/m/$slug'
      path: '/m/$slug'
      fullPath: '/m/$slug'
      preLoaderRoute: typeof MSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$slug': {
      id: '/book/$slug'
      path: '/book/$slug'
      fullPath: '/book/$slug'
      preLoaderRoute: typeof BookSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/m/$slug/': {
      id: '/m/$slug/'
      path: '/'
      fullPath: '/m/$slug/'
      preLoaderRoute: typeof MSlugIndexRouteImport
      parentRoute: typeof MSlugRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/m/$slug/reviews': {
      id: '/m/$slug/reviews'
      path: '/reviews'
      fullPath: '/m/$slug/reviews'
      preLoaderRoute: typeof MSlugReviewsRouteImport
      parentRoute: typeof MSlugRoute
    }
    '/m/$slug/auth': {
      id: '/m/$slug/auth'
      path: '/auth'
      fullPath: '/m/$slug/auth'
      preLoaderRoute: typeof MSlugAuthRouteImport
      parentRoute: typeof MSlugRoute
    }
    '/m/$slug/account': {
      id: '/m/$slug/account'
      path: '/account'
      fullPath: '/m/$slug/account'
      preLoaderRoute: typeof MSlugAccountRouteImport
      parentRoute: typeof MSlugRoute
    }
    '/m/$slug/about': {
      id: '/m/$slug/about'
      path: '/about'
      fullPath: '/m/$slug/about'
      preLoaderRoute: typeof MSlugAboutRouteImport
      parentRoute: typeof MSlugRoute
    }
    '/_authenticated/dashboard/treatments': {
      id: '/_authenticated/dashboard/treatments'
      path: '/treatments'
      fullPath: '/dashboard/treatments'
      preLoaderRoute: typeof AuthenticatedDashboardTreatmentsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/reviews': {
      id: '/_authenticated/dashboard/reviews'
      path: '/reviews'
      fullPath: '/dashboard/reviews'
      preLoaderRoute: typeof AuthenticatedDashboardReviewsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/payments': {
      id: '/_authenticated/dashboard/payments'
      path: '/payments'
      fullPath: '/dashboard/payments'
      preLoaderRoute: typeof AuthenticatedDashboardPaymentsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/medical-forms': {
      id: '/_authenticated/dashboard/medical-forms'
      path: '/medical-forms'
      fullPath: '/dashboard/medical-forms'
      preLoaderRoute: typeof AuthenticatedDashboardMedicalFormsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/locations': {
      id: '/_authenticated/dashboard/locations'
      path: '/locations'
      fullPath: '/dashboard/locations'
      preLoaderRoute: typeof AuthenticatedDashboardLocationsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/consent-forms': {
      id: '/_authenticated/dashboard/consent-forms'
      path: '/consent-forms'
      fullPath: '/dashboard/consent-forms'
      preLoaderRoute: typeof AuthenticatedDashboardConsentFormsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/clinic': {
      id: '/_authenticated/dashboard/clinic'
      path: '/clinic'
      fullPath: '/dashboard/clinic'
      preLoaderRoute: typeof AuthenticatedDashboardClinicRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/categories': {
      id: '/_authenticated/dashboard/categories'
      path: '/categories'
      fullPath: '/dashboard/categories'
      preLoaderRoute: typeof AuthenticatedDashboardCategoriesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/branding': {
      id: '/_authenticated/dashboard/branding'
      path: '/branding'
      fullPath: '/dashboard/branding'
      preLoaderRoute: typeof AuthenticatedDashboardBrandingRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/bookings': {
      id: '/_authenticated/dashboard/bookings'
      path: '/bookings'
      fullPath: '/dashboard/bookings'
      preLoaderRoute: typeof AuthenticatedDashboardBookingsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/bio': {
      id: '/_authenticated/dashboard/bio'
      path: '/bio'
      fullPath: '/dashboard/bio'
      preLoaderRoute: typeof AuthenticatedDashboardBioRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/availability': {
      id: '/_authenticated/dashboard/availability'
      path: '/availability'
      fullPath: '/dashboard/availability'
      preLoaderRoute: typeof AuthenticatedDashboardAvailabilityRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
  }
}

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardAvailabilityRoute: typeof AuthenticatedDashboardAvailabilityRoute
  AuthenticatedDashboardBioRoute: typeof AuthenticatedDashboardBioRoute
  AuthenticatedDashboardBookingsRoute: typeof AuthenticatedDashboardBookingsRoute
  AuthenticatedDashboardBrandingRoute: typeof AuthenticatedDashboardBrandingRoute
  AuthenticatedDashboardCategoriesRoute: typeof AuthenticatedDashboardCategoriesRoute
  AuthenticatedDashboardClinicRoute: typeof AuthenticatedDashboardClinicRoute
  AuthenticatedDashboardConsentFormsRoute: typeof AuthenticatedDashboardConsentFormsRoute
  AuthenticatedDashboardLocationsRoute: typeof AuthenticatedDashboardLocationsRoute
  AuthenticatedDashboardMedicalFormsRoute: typeof AuthenticatedDashboardMedicalFormsRoute
  AuthenticatedDashboardPaymentsRoute: typeof AuthenticatedDashboardPaymentsRoute
  AuthenticatedDashboardReviewsRoute: typeof AuthenticatedDashboardReviewsRoute
  AuthenticatedDashboardTreatmentsRoute: typeof AuthenticatedDashboardTreatmentsRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardAvailabilityRoute:
      AuthenticatedDashboardAvailabilityRoute,
    AuthenticatedDashboardBioRoute: AuthenticatedDashboardBioRoute,
    AuthenticatedDashboardBookingsRoute: AuthenticatedDashboardBookingsRoute,
    AuthenticatedDashboardBrandingRoute: AuthenticatedDashboardBrandingRoute,
    AuthenticatedDashboardCategoriesRoute:
      AuthenticatedDashboardCategoriesRoute,
    AuthenticatedDashboardClinicRoute: AuthenticatedDashboardClinicRoute,
    AuthenticatedDashboardConsentFormsRoute:
      AuthenticatedDashboardConsentFormsRoute,
    AuthenticatedDashboardLocationsRoute: AuthenticatedDashboardLocationsRoute,
    AuthenticatedDashboardMedicalFormsRoute:
      AuthenticatedDashboardMedicalFormsRoute,
    AuthenticatedDashboardPaymentsRoute: AuthenticatedDashboardPaymentsRoute,
    AuthenticatedDashboardReviewsRoute: AuthenticatedDashboardReviewsRoute,
    AuthenticatedDashboardTreatmentsRoute:
      AuthenticatedDashboardTreatmentsRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface MSlugRouteChildren {
  MSlugAboutRoute: typeof MSlugAboutRoute
  MSlugAccountRoute: typeof MSlugAccountRoute
  MSlugAuthRoute: typeof MSlugAuthRoute
  MSlugReviewsRoute: typeof MSlugReviewsRoute
  MSlugIndexRoute: typeof MSlugIndexRoute
}

const MSlugRouteChildren: MSlugRouteChildren = {
  MSlugAboutRoute: MSlugAboutRoute,
  MSlugAccountRoute: MSlugAccountRoute,
  MSlugAuthRoute: MSlugAuthRoute,
  MSlugReviewsRoute: MSlugReviewsRoute,
  MSlugIndexRoute: MSlugIndexRoute,
}

const MSlugRouteWithChildren = MSlugRoute._addFileChildren(MSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  BookSlugRoute: BookSlugRoute,
  MSlugRoute: MSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
